### ISSUE TITLE
./build.sh not removing deleted commands from src/SlashCommands.ts

### ISSUE THREAD

**Issue by FordFriedel** [Paris-Developers/Mirror-TS#24]

**Comment by FordFriedel** [comment]
So on the bitvise SFTP window I noticed that there is a file called SlashCommands.ts which does not exist on the windows builds of mirror. Then during the build process it will stop and say

```
src/slashcommands/SlashCommands.ts cannot find module './DeletedCommand'
```

**Comment by CPhantasm** [comment]
Just remove any of the old holder files. They weren't tracked by GitHub so they won't be removed automatically, but they haven't been in use since the first typescript PR. They will never be recreated once removed.
